version: "3"
services:
    graph-node-indexer:
        container_name: celo-graphprotocol-hosted-docker
        image: graphprotocol/graph-node:v0.25.2
        ports:
            - "8020:8020"
        depends_on:
            - ipfs
            - postgres
        environment:
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            ETHEREUM_POLLING_INTERVAL: ${ETHEREUM_POLLING_INTERVAL}
            GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: ${GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE}
            ETHEREUM_BLOCK_BATCH_SIZE: ${ETHEREUM_BLOCK_BATCH_SIZE}
            GRAPH_GRAPHQL_QUERY_TIMEOUT: ${GRAPH_GRAPHQL_QUERY_TIMEOUT}
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            ethereum: "${CHAIN_NETWORK}:no_eip1898,archive,traces:${NETWORK_NODE_URL}"
            RUST_LOG: info
    graph-node-query-0:
        container_name: celo-graph-query-0
        image: graphprotocol/graph-node:v0.25.2
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8030:8030"
            - "8040:8040"
        depends_on:
            - ipfs
            - postgres
        environment:
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            node_role: query-node
            node_id: quer_node_0
            GRAPH_LOG_QUERY_TIMING: '${GRAPH_LOG_QUERY_TIMING}'
            DISABLE_BLOCK_INGESTOR: '${DISABLE_BLOCK_INGESTOR}'
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            ethereum: "${CHAIN_NETWORK}:no_eip1898,archive,traces:${NETWORK_NODE_URL}"
            RUST_LOG: info
    graph-node-query-1:
        container_name: celo-graph-query-1
        image: graphprotocol/graph-node:v0.25.2
        ports:
            - "9000:8000"
            - "9001:8001"
            - "9030:8030"
            - "9040:8040"
        depends_on:
            - ipfs
            - postgres
        environment:
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            node_role: query-node
            node_id: quer_node_0
            GRAPH_LOG_QUERY_TIMING: '${GRAPH_LOG_QUERY_TIMING}'
            DISABLE_BLOCK_INGESTOR: '${DISABLE_BLOCK_INGESTOR}'
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            ethereum: "${CHAIN_NETWORK}:no_eip1898,archive,traces:${NETWORK_NODE_URL}"
            RUST_LOG: info
    ipfs:
        container_name: ipfs
        image: ipfs/go-ipfs:v0.4.23
        ports:
            - "5001:5001"
        volumes:
            - ./data/ipfs:/data/ipfs
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
