version: "3"
networks:
    monitor-net:
        driver: bridge

services:
    graph-node-indexer:
        container_name: graph-indexer
        image: graphprotocol/graph-node:v0.26.0
        ports:
            - "9020:8020"
        depends_on:
            - ipfs
            - postgres
        networks:
            - monitor-net
        logging:
            driver: "json-file"
            options:
                max-size: "2g"
                max-file: "10"
        environment:
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            ETHEREUM_POLLING_INTERVAL: ${ETHEREUM_POLLING_INTERVAL}
            GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: ${GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE}
            ETHEREUM_BLOCK_BATCH_SIZE: ${ETHEREUM_BLOCK_BATCH_SIZE}
            GRAPH_GRAPHQL_QUERY_TIMEOUT: ${GRAPH_GRAPHQL_QUERY_TIMEOUT}
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            ethereum: "${CHAIN_NETWORK}:no_eip1898,archive,traces:${NETWORK_NODE_URL}"
            RUST_LOG: info
    graph-node-query-0:
        container_name: graph-query-0
        image: graphprotocol/graph-node:v0.26.0
        ports:
            - "9000:8000"
            - "9030:8030"
        depends_on:
            - ipfs
            - postgres
        networks:
            - monitor-net
        logging:
            driver: "json-file"
            options:
                max-size: "1g"
                max-file: "3"
        environment:
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            node_role: query-node
            node_id: ethereum_query_node_0
            GRAPH_LOG_QUERY_TIMING: '${GRAPH_LOG_QUERY_TIMING}'
            DISABLE_BLOCK_INGESTOR: '${DISABLE_BLOCK_INGESTOR}'
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            ethereum: "${CHAIN_NETWORK}:no_eip1898,archive,traces:${NETWORK_NODE_URL}"
            RUST_LOG: info
    graph-node-query-1:
        container_name: graph-query-1
        image: graphprotocol/graph-node:v0.26.0
        ports:
            - "9001:8000"
            - "9031:8030"
        depends_on:
            - ipfs
            - postgres
        networks:
            - monitor-net
        logging:
            driver: "json-file"
            options:
                max-size: "1g"
                max-file: "3"
        environment:
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            node_role: query-node
            node_id: ethereum_query_node_1
            GRAPH_LOG_QUERY_TIMING: '${GRAPH_LOG_QUERY_TIMING}'
            DISABLE_BLOCK_INGESTOR: '${DISABLE_BLOCK_INGESTOR}'
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            ethereum: "${CHAIN_NETWORK}:no_eip1898,archive,traces:${NETWORK_NODE_URL}"
            RUST_LOG: info
    ipfs:
        container_name: ipfs
        image: ipfs/go-ipfs:v0.4.23
        ports:
            - "6001:5001"
        volumes:
            - /mnt/.ethereum/ipfs:/data/ipfs
        networks:
            - monitor-net
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - "6432:5432"
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - monitor-net
        volumes:
            - /mnt/.ethereum/postgres:/var/lib/postgresql/data
