version: "3"
networks:
    monitor-net:
        driver: bridge

services:
    graph-node-indexer:
        container_name: graph-node-indexer
        image: graphprotocol/graph-node:v0.31.0
        ports:
            - "8020:8020"
        depends_on:
            - ipfs
            - postgres
        networks:
            - monitor-net
        logging:
            driver: "json-file"
            options:
                max-size: "2g"
                max-file: "10"
        volumes:
            - ./graph-node-configs:/root/graph-node-configs/
        environment:
            GRAPH_NODE_CONFIG: /root/graph-node-configs/config.toml
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            ETHEREUM_POLLING_INTERVAL: ${ETHEREUM_POLLING_INTERVAL}
            GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: ${GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE}
            ETHEREUM_BLOCK_BATCH_SIZE: ${ETHEREUM_BLOCK_BATCH_SIZE}
            GRAPH_GRAPHQL_QUERY_TIMEOUT: ${GRAPH_GRAPHQL_QUERY_TIMEOUT}
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            RUST_LOG: info
    graph-node-query-0:
        container_name: graph-node-query-0
        image: graphprotocol/graph-node:v0.31.0
        ports:
            - "8000:8000"
            - "8030:8030"
        depends_on:
            - ipfs
            - postgres
        networks:
            - monitor-net
        logging:
            driver: "json-file"
            options:
                max-size: "1g"
                max-file: "3"
        volumes:
            - ./graph-node-configs:/root/graph-node-configs/
        environment:
            GRAPH_NODE_CONFIG: /root/graph-node-configs/config.toml
            postgres_host: ${POSTGRES_HOST}
            postgres_user: ${POSTGRES_USER}
            postgres_pass: "${POSTGRES_PASSWORD}"
            postgres_db: ${POSTGRES_DB}
            ipfs: "ipfs:5001"
            node_role: query-node
            node_id: graph-node-query-0
            GRAPH_LOG_QUERY_TIMING: '${GRAPH_LOG_QUERY_TIMING}'
            DISABLE_BLOCK_INGESTOR: '${DISABLE_BLOCK_INGESTOR}'
            EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: ${EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE}
            RUST_LOG: info
    ipfs:
        container_name: ipfs
        image: ipfs/go-ipfs:v0.4.23
        ports:
            - "5001:5001"
        volumes:
            - /mnt/.celo/ipfs:/data/ipfs
        networks:
            - monitor-net
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - "5432:5432"
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - monitor-net
        volumes:
            - /mnt/.celo/postgres:/var/lib/postgresql/data
